using System;
using System.Collections.Generic;
using System.Text;

namespace TryIT.SqlAdo.MicrosoftSqlClient.Attributes
{
    /// <summary>  
    /// Indicate if the column is identity column in SQL, which means the value will be generated by SQL and cannot be inserted or updated.
    /// </summary>  
    [AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = true)]
    public sealed class SqlIdentityAttribute : Attribute
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SqlOutputAttribute"/> class, specifying whether the
        /// associated SQL entity is returned.
        /// </summary>
        public SqlIdentityAttribute()
        {
        }
    }
}
