using System.Collections.Generic;

namespace ActiveDirectory.Constants
{
    internal class AttributeMap
    {
        public class User
        {
            public static readonly string DistinguishedName = "DistinguishedName";
            public static readonly string DisplayName = "DisplayName";
            public static readonly string GivenName = "GivenName";
            public static readonly string LastName = "LastName";
            public static readonly string EmployeeId = "EmployeeId";
            public static readonly string UserLogin = "UserLogin";
            public static readonly string EmailAddress = "EmailAddress";
            public static readonly string Manager_DistinguishedName = "Manager_DistinguishedName";
            public static readonly string MemberOf_DistinguishedName = "MemberOf_DistinguishedName";
            public static readonly string ExpirationDate = "ExpirationDate";
            public static readonly string AccountLockoutTime = "AccountLockoutTime";
            public static readonly string LastPasswordSet = "LastPasswordSet";
            public static readonly string CreationDate = "CreationDate";
            public static readonly string UserAccountControl = "UserAccountControl";

            public static Dictionary<string, string> BaseMap
            {
                get
                {
                    return new Dictionary<string, string>
                    {
                        {DistinguishedName, "distinguishedName" },
                        {DisplayName, "displayName" },
                        {UserLogin, "sAMAccountName" },
                        {EmployeeId, "employeeID" },
                        {EmailAddress, "userPrincipalName" }                    
                    };
                }
            }

            public static Dictionary<string, string> UserManagerMap
            {
                get
                {
                    return new Dictionary<string, string>
                    {
                        {DistinguishedName, "distinguishedName" },
                        {Manager_DistinguishedName, "manager" }
                    };
                }
            }
            public static Dictionary<string, string> UserGroupMap
            {
                get
                {
                    return new Dictionary<string, string>
                    {
                        {DistinguishedName, "distinguishedName" },
                        {MemberOf_DistinguishedName, "memberOf" }
                    };
                }
            }

            public static Dictionary<string, string> DetailMap
            {
                get
                {
                    return new Dictionary<string, string>
                    {
                        {DistinguishedName, "distinguishedName" },
                        {DisplayName, "displayName" },
                        {GivenName, "givenname" },
                        {LastName, "sn" },
                        {UserLogin, "sAMAccountName" },
                        {EmployeeId, "employeeID" },
                        {EmailAddress, "userPrincipalName" },
                        {UserAccountControl, "userAccountControl" },
                        //{Manager_DistinguishedName, "manager" },
                        //{MemberOf_DistinguishedName, "memberOf" },
                        {ExpirationDate, "accountexpires" },
                        {AccountLockoutTime, "lockouttime" },
                        {LastPasswordSet, "pwdlastset" },
                        {CreationDate, "whencreated" }
                    };
                }
            }

            /// <summary>
            /// user's manager get general information only, exclude memberof info, exclude manager's manager info
            /// </summary>
            public static Dictionary<string, string> ManagerMap
            {
                get
                {
                    return new Dictionary<string, string>
                    {
                        {DistinguishedName, "distinguishedName" },
                        {DisplayName, "displayName" },
                        {GivenName, "givenname" },
                        {LastName, "sn" },
                        {UserLogin, "sAMAccountName" },
                        {EmployeeId, "employeeID" },
                        {EmailAddress, "userPrincipalName" }
                        //{Manager_DistinguishedName, "manager" },
                        //{MemberOf_DistinguishedName, "memberOf" },
                        //{ExpirationDate, "accountexpires" },
                        //{AccountLockoutTime, "lockouttime" },
                        //{LastPasswordSet, "pwdlastset" },
                        //{CreationDate, "whencreated" }
                    };
                }
            }
        }

        public class Group
        {
            public static readonly string DistinguishedName = "DistinguishedName";
            public static readonly string Name = "Name";
            public static readonly string Description = "Description";
            public static readonly string Mail = "Mail";
            public static readonly string Member_DistinguishedName = "Member_DistinguishedName";

            public static Dictionary<string, string> Map
            {
                get
                {
                    return new Dictionary<string, string>
                    {
                        {DistinguishedName, "distinguishedName" },
                        {Name, "name" },
                        {Description, "description" },
                        {Mail, "mail" },
                        {Member_DistinguishedName, "member" }
                    };
                }
            }
        }

        #region ad attributes
        /*
        accountExpires
        accountNameHistory
        aCSPolicyName
        adminCount
        adminDescription
        adminDisplayName
        allowedAttributes
        allowedAttributesEffective
        allowedChildClasses
        allowedChildClassesEffective
        altRecipient
        altRecipientBL
        altSecurityIdentities
        assistant
        attributeCertificate
        attributeCertificateAttribute
        audio
        authOrig
        authOrigBL
        autoReply
        autoReplyMessage
        badPasswordTime
        badPwdCount
        bridgeheadServerListBL
        businessCategory
        businessRoles
        c
        canonicalName
        carLicense
        cn
        co
        codePage
        comment
        company
        controlAccessRights
        countryCode
        createTimeStamp
        dBCSPwd
        defaultClassStore
        deletedItemFlags
        delivContLength
        deliverAndRedirect
        deliveryMechanism
        delivExtContTypes
        department
        departmentNumber
        description
        desktopProfile
        destinationIndicator
        directReports
        displayName
        displayNamePrintable
        distinguishedName
        division
        dLMemDefault
        dLMemRejectPerms
        dLMemRejectPermsBL
        dLMemSubmitPerms
        dLMemSubmitPermsBL
        dnQualifier
        dSASignature
        dSCorePropagationData
        dynamicLDAPServer
        employeeID
        employeeNumber
        employeeType
        enabledProtocols
        expirationTime
        extensionAttribute1
        extensionAttribute10
        extensionAttribute11
        extensionAttribute12
        extensionAttribute13
        extensionAttribute14
        extensionAttribute15
        extensionAttribute2
        extensionAttribute3
        extensionAttribute4
        extensionAttribute5
        extensionAttribute6
        extensionAttribute7
        extensionAttribute8
        extensionAttribute9
        extensionData
        extensionName
        facsimileTelephoneNumber
        flags
        folderPathname
        formData
        forwardingAddress
        fromEntry
        frsComputerReferenceBL
        fRSMemberReferenceBL
        fSMORoleOwner
        garbageCollPeriod
        gecos
        generationQualifier
        gidNumber
        givenName
        groupMembershipSAM
        groupPriority
        groupsToIgnore
        heuristics
        homeDirectory
        homeDrive
        homeMDB
        homeMTA
        homePhone
        homePostalAddress
        houseIdentifier
        importedFrom
        info
        initials
        instanceType
        internationalISDNNumber
        internetEncoding
        ipPhone
        isCriticalSystemObject
        isDeleted
        isPrivilegeHolder
        isRecycled
        jpegPhoto
        kMServer
        l
        labeledURI
        language
        languageCode
        lastKnownParent
        lastLogoff
        lastLogon
        lastLogonTimestamp
        legacyExchangeDN
        lmPwdHistory
        localeID
        lockoutTime
        loginShell
        logonCount
        logonHours
        logonWorkstation
        mail
        mailNickname
        managedObjects
        manager
        mAPIRecipient
        masteredBy
        maxStorage
        mDBOverHardQuotaLimit
        mDBOverQuotaLimit
        mDBStorageQuota
        mDBUseDefaults
        memberOf
        mhsORAddress
        middleName
        mobile
        modifyTimeStamp
        msCOM-PartitionSetLink
        msCOM-UserLink
        msCOM-UserPartitionSetLink
        msDFSR-ComputerReferenceBL
        msDFSR-MemberReferenceBL
        msDRM-IdentityCertificate
        msDS-AllowedToActOnBehalfOfOtherIdentity
        msDS-AllowedToDelegateTo
        msDS-Approx-Immed-Subordinates
        msDS-AssignedAuthNPolicy
        msDS-AssignedAuthNPolicySilo
        msDS-AuthenticatedAtDC
        msDS-AuthenticatedToAccountlist
        msDS-AuthNPolicySiloMembersBL
        msDS-Cached-Membership
        msDS-Cached-Membership-Time-Stamp
        msDS-ClaimSharesPossibleValuesWithBL
        msDS-CloudAnchor
        msDS-cloudExtensionAttribute1
        msDS-cloudExtensionAttribute10
        msDS-cloudExtensionAttribute11
        msDS-cloudExtensionAttribute12
        msDS-cloudExtensionAttribute13
        msDS-cloudExtensionAttribute14
        msDS-cloudExtensionAttribute15
        msDS-cloudExtensionAttribute16
        msDS-cloudExtensionAttribute17
        msDS-cloudExtensionAttribute18
        msDS-cloudExtensionAttribute19
        msDS-cloudExtensionAttribute2
        msDS-cloudExtensionAttribute20
        msDS-cloudExtensionAttribute3
        msDS-cloudExtensionAttribute4
        msDS-cloudExtensionAttribute5
        msDS-cloudExtensionAttribute6
        msDS-cloudExtensionAttribute7
        msDS-cloudExtensionAttribute8
        msDS-cloudExtensionAttribute9
        mS-DS-ConsistencyChildCount
        mS-DS-ConsistencyGuid
        mS-DS-CreatorSID
        msDS-EnabledFeatureBL
        msDS-ExternalDirectoryObjectId
        msDS-FailedInteractiveLogonCount
        msDS-FailedInteractiveLogonCountAtLastSuccessfulLogon
        msDS-GeoCoordinatesAltitude
        msDS-GeoCoordinatesLatitude
        msDS-GeoCoordinatesLongitude
        msDS-HABSeniorityIndex
        msDS-HostServiceAccountBL
        msDS-IsDomainFor
        msDS-IsFullReplicaFor
        msDS-IsPartialReplicaFor
        msDS-IsPrimaryComputerFor
        msDS-KeyCredentialLink
        msDS-KeyPrincipalBL
        msDS-KeyVersionNumber
        msDS-KrbTgtLinkBl
        msDS-LastFailedInteractiveLogonTime
        msDS-LastKnownRDN
        msDS-LastSuccessfulInteractiveLogonTime
        msDS-LocalEffectiveDeletionTime
        msDS-LocalEffectiveRecycleTime
        msDs-masteredBy
        msds-memberOfTransitive
        msDS-MembersForAzRoleBL
        msDS-MembersOfResourcePropertyListBL
        msds-memberTransitive
        msDS-NCReplCursors
        msDS-NCReplInboundNeighbors
        msDS-NCReplOutboundNeighbors
        msDS-NC-RO-Replica-Locations-BL
        msDS-NcType
        msDS-NonMembersBL
        msDS-ObjectReferenceBL
        msDS-ObjectSoa
        msDS-OIDToGroupLinkBl
        msDS-OperationsForAzRoleBL
        msDS-OperationsForAzTaskBL
        msDS-parentdistname
        msDS-PhoneticCompanyName
        msDS-PhoneticDepartment
        msDS-PhoneticDisplayName
        msDS-PhoneticFirstName
        msDS-PhoneticLastName
        msDS-PrimaryComputer
        msDS-PrincipalName
        msDS-PSOApplied
        msDS-ReplAttributeMetaData
        msDS-ReplValueMetaData
        msDS-ReplValueMetaDataExt
        msDS-ResultantPSO
        msDS-RevealedDSAs
        msDS-RevealedListBL
        msDS-SecondaryKrbTgtNumber
        msDS-Site-Affinity
        msDS-SourceAnchor
        msDS-SourceObjectDN
        msDS-SupportedEncryptionTypes
        msDS-SyncServerUrl
        msDS-TasksForAzRoleBL
        msDS-TasksForAzTaskBL
        msDS-TDOEgressBL
        msDS-TDOIngressBL
        msds-tokenGroupNames
        msds-tokenGroupNamesGlobalAndUniversal
        msds-tokenGroupNamesNoGCAcceptable
        msDS-User-Account-Control-Computed
        msDS-UserPasswordExpiryTimeComputed
        msDS-ValueTypeReferenceBL
        msExchAcceptedDomainBL
        msExchAccountForestBL
        msExchADCGlobalNames
        msExchAddressBookFlags
        msExchAddressBookPolicyLink
        msExchAdministrativeUnitBL
        msExchAdministrativeUnitLink
        msExchAggregationSubscriptionCredential
        msExchALObjectVersion
        msExchAlternateMailboxes
        msExchApprovalApplicationLink
        msExchArbitrationMailbox
        msExchArchiveAddress
        msExchArchiveDatabaseBL
        msExchArchiveDatabaseLink
        msExchArchiveDatabaseLinkSL
        msExchArchiveGUID
        msExchArchiveName
        msExchArchiveQuota
        msExchArchiveRelease
        msExchArchiveStatus
        msExchArchiveWarnQuota
        msExchAssistantName
        msExchAssociatedAcceptedDomainBL
        msExchAuditAdmin
        msExchAuditDelegate
        msExchAuditDelegateAdmin
        msExchAuditOwner
        msExchAuthPolicyBL
        msExchAuthPolicyLink
        msExchAuxMailboxParentObjectIdBL
        msExchAuxMailboxParentObjectIdLink
        msExchAvailabilityOrgWideAccountBL
        msExchAvailabilityPerUserAccountBL
        msExchBlockedSendersHash
        msExchBypassAudit
        msExchBypassModerationBL
        msExchBypassModerationFromDLMembersBL
        msExchBypassModerationFromDLMembersLink
        msExchBypassModerationLink
        msExchCalculatedTargetAddress
        msExchCalendarLoggingQuota
        msExchCalendarRepairDisabled
        msExchCanaryData0
        msExchCanaryData1
        msExchCanaryData2
        msExchCapabilityIdentifiers
        msExchCatchAllRecipientBL
        msExchCoManagedObjectsBL
        msExchConferenceMailboxBL
        msExchConfigurationUnitBL
        msExchConfigurationXML
        msExchContentConversionSettings
        msExchControllingZone
        msExchCorrelationId
        msExchCU
        msExchCustomProxyAddresses
        msExchDataEncryptionPolicyBL
        msExchDataEncryptionPolicyLink
        msExchDefaultPublicFolderMailbox
        msExchDelegateListBL
        msExchDelegateListLink
        msExchDeviceAccessControlRuleBL
        msExchDirsyncAuthorityMetadata
        msExchDirsyncID
        msExchDirsyncSourceObjectClass
        msExchDirsyncStatusAck
        msExchDisabledArchiveDatabaseLink
        msExchDisabledArchiveDatabaseLinkSL
        msExchDisabledArchiveGUID
        msExchDumpsterQuota
        msExchDumpsterWarningQuota
        msExchEdgeSyncConfigFlags
        msExchEdgeSyncCookies
        msExchEdgeSyncRetryCount
        msExchEdgeSyncSourceGuid
        msExchELCExpirySuspensionEnd
        msExchELCExpirySuspensionStart
        msExchELCMailboxFlags
        msExchEnableModeration
        msExchEvictedMemebersBL
        msExchEwsApplicationAccessPolicy
        msExchEwsEnabled
        msExchEwsExceptions
        msExchEwsWellKnownApplicationPolicies
        msExchExpansionServerName
        msExchExtensionAttribute16
        msExchExtensionAttribute17
        msExchExtensionAttribute18
        msExchExtensionAttribute19
        msExchExtensionAttribute20
        msExchExtensionAttribute21
        msExchExtensionAttribute22
        msExchExtensionAttribute23
        msExchExtensionAttribute24
        msExchExtensionAttribute25
        msExchExtensionAttribute26
        msExchExtensionAttribute27
        msExchExtensionAttribute28
        msExchExtensionAttribute29
        msExchExtensionAttribute30
        msExchExtensionAttribute31
        msExchExtensionAttribute32
        msExchExtensionAttribute33
        msExchExtensionAttribute34
        msExchExtensionAttribute35
        msExchExtensionAttribute36
        msExchExtensionAttribute37
        msExchExtensionAttribute38
        msExchExtensionAttribute39
        msExchExtensionAttribute40
        msExchExtensionAttribute41
        msExchExtensionAttribute42
        msExchExtensionAttribute43
        msExchExtensionAttribute44
        msExchExtensionAttribute45
        msExchExtensionCustomAttribute1
        msExchExtensionCustomAttribute2
        msExchExtensionCustomAttribute3
        msExchExtensionCustomAttribute4
        msExchExtensionCustomAttribute5
        msExchExternalDirectoryObjectId
        msExchExternalOOFOptions
        msExchExternalSyncState
        msExchFBURL
        msExchForeignGroupSID
        msExchForestModeFlag
        msExchGenericForwardingAddress
        msExchGroupExternalMemberCount
        msExchGroupMemberCount
        msExchGroupSecurityFlags
        msExchHABRootDepartmentBL
        msExchHABRootDepartmentLink
        msExchHABShowInDepartments
        msExchHideFromAddressLists
        msExchHomeMDBSL
        msExchHomeMTASL
        msExchHomeServerName
        msExchHouseIdentifier
        msExchHygieneConfigurationMalwareBL
        msExchHygieneConfigurationSpamBL
        msExchIMACL
        msExchIMAddress
        msExchIMAP4Settings
        msExchIMAPOWAURLPrefixOverride
        msExchIMMetaPhysicalURL
        msExchImmutableId
        msExchImmutableSid
        msExchIMPhysicalURL
        msExchIMVirtualServer
        msExchInconsistentState
        msExchIntendedMailboxPlanBL
        msExchIntendedMailboxPlanLink
        msExchInterruptUserOnAuditFailure
        msExchIsMSODirsynced
        msExchLabeledURI
        msExchLastExchangeChangedTime
        msExchLicenseToken
        msExchLitigationHoldDate
        msExchLitigationHoldOwner
        msExchLocalizationFlags
        msExchMailboxAuditEnable
        msExchMailboxAuditLastAdminAccess
        msExchMailboxAuditLastDelegateAccess
        msExchMailboxAuditLastExternalAccess
        msExchMailboxAuditLogAgeLimit
        msExchMailboxContainerGuid
        msExchMailboxFolderSet
        msExchMailboxFolderSet2
        msExchMailboxGuid
        msExchMailboxMoveBatchName
        msExchMailboxMoveFlags
        msExchMailboxMoveRemoteHostName
        msExchMailboxMoveSourceArchiveMDBBL
        msExchMailboxMoveSourceArchiveMDBLink
        msExchMailboxMoveSourceArchiveMDBLinkSL
        msExchMailboxMoveSourceMDBBL
        msExchMailboxMoveSourceMDBLink
        msExchMailboxMoveSourceMDBLinkSL
        msExchMailboxMoveSourceUserBL
        msExchMailboxMoveStatus
        msExchMailboxMoveStorageMDBBL
        msExchMailboxMoveTargetArchiveMDBBL
        msExchMailboxMoveTargetArchiveMDBLink
        msExchMailboxMoveTargetArchiveMDBLinkSL
        msExchMailboxMoveTargetMDBBL
        msExchMailboxMoveTargetMDBLink
        msExchMailboxMoveTargetMDBLinkSL
        msExchMailboxMoveTargetUserBL
        msExchMailboxOABVirtualDirectoriesLink
        msExchMailboxPlanType
        msExchMailboxRelease
        msExchMailboxSecurityDescriptor
        msExchMailboxTemplateLink
        msExchMailboxUrl
        msExchManagementSettings
        msExchMasterAccountSid
        msExchMaxBlockedSenders
        msExchMaxSafeSenders
        msExchMDBAvailabilityGroupConfigurationBL
        msExchMDBRulesQuota
        msExchMessageHygieneFlags
        msExchMessageHygieneSCLDeleteThreshold
        msExchMessageHygieneSCLJunkThreshold
        msExchMessageHygieneSCLQuarantineThreshold
        msExchMessageHygieneSCLRejectThreshold
        msExchMobileAllowedDeviceIDs
        msExchMobileBlockedDeviceIDs
        msExchMobileDebugLogging
        msExchMobileMailboxFlags
        msExchMobileMailboxPolicyLink
        msExchMobileRemoteDocumentsAllowedServersBL
        msExchMobileRemoteDocumentsBlockedServersBL
        msExchMobileRemoteDocumentsInternalDomainSuffixListBL
        msExchMobileSettings
        msExchModeratedByLink
        msExchModeratedObjectsBL
        msExchModerationFlags
        msExchMultiMailboxDatabasesBL
        msExchMultiMailboxDatabasesLink
        msExchMultiMailboxGUIDs
        msExchMultiMailboxLocationsBL
        msExchMultiMailboxLocationsLink
        msExchOABGeneratingMailboxBL
        msExchObjectCountQuota
        msExchObjectID
        msExchOmaAdminExtendedSettings
        msExchOmaAdminWirelessEnable
        msExchOnPremiseObjectGuid
        msExchOrganizationsAddressBookRootsBL
        msExchOrganizationsGlobalAddressListsBL
        msExchOrganizationsTemplateRootsBL
        msExchOrganizationUpgradeRequest
        msExchOrganizationUpgradeStatus
        msExchOriginatingForest
        msExchOURoot
        msExchOWAAllowedFileTypesBL
        msExchOWAAllowedMimeTypesBL
        msExchOWABlockedFileTypesBL
        msExchOWABlockedMIMETypesBL
        msExchOWAForceSaveFileTypesBL
        msExchOWAForceSaveMIMETypesBL
        msExchOWAPolicy
        msExchOWARemoteDocumentsAllowedServersBL
        msExchOWARemoteDocumentsBlockedServersBL
        msExchOWARemoteDocumentsInternalDomainSuffixListBL
        msExchOWASettings
        msExchOWATranscodingFileTypesBL
        msExchOWATranscodingMimeTypesBL
        msExchParentPlanBL
        msExchParentPlanLink
        msExchPartnerGroupID
        msExchPfRootUrl
        msExchPoliciesExcluded
        msExchPoliciesIncluded
        msExchPolicyEnabled
        msExchPolicyOptionList
        msExchPOP3Settings
        msExchPreviousAccountSid
        msExchPreviousArchiveDatabase
        msExchPreviousArchiveDatabaseSL
        msExchPreviousHomeMDB
        msExchPreviousHomeMDBSL
        msExchPreviousMailboxGuid
        msExchPreviousRecipientTypeDetails
        msExchProvisioningFlags
        msExchProvisioningTags
        msExchProxyCustomProxy
        msExchPublicFolderMailbox
        msExchPublicFolderSmtpAddress
        msExchQueryBaseDN
        msExchRBACPolicyBL
        msExchRBACPolicyLink
        msExchRecipientDisplayType
        msExchRecipientSoftDeletedStatus
        msExchRecipientTypeDetails
        msExchRecipientValidatorCookies
        msExchRecipLimit
        msExchRemoteRecipientType
        msExchRequireAuthToSendTo
        msExchResourceCapacity
        msExchResourceDisplay
        msExchResourceGUID
        msExchResourceMetaData
        msExchResourceProperties
        msExchResourceSearchProperties
        msExchRetentionComment
        msExchRetentionURL
        msExchRMSComputerAccountsBL
        msExchRMSComputerAccountsLink
        msExchRoleGroupType
        msExchSafeRecipientsHash
        msExchSafeSendersHash
        msExchSendAsAddresses
        msExchSenderHintTranslations
        msExchServerAssociationBL
        msExchServerAssociationLink
        msExchServerSiteBL
        msExchSetupStatus
        msExchShadowAssistantName
        msExchShadowC
        msExchShadowCo
        msExchShadowCompany
        msExchShadowCountryCode
        msExchShadowDepartment
        msExchShadowDisplayName
        msExchShadowFacsimileTelephoneNumber
        msExchShadowGivenName
        msExchShadowHomePhone
        msExchShadowInfo
        msExchShadowInitials
        msExchShadowL
        msExchShadowMailNickname
        msExchShadowManagerLink
        msExchShadowMobile
        msExchShadowOtherFacsimileTelephone
        msExchShadowOtherHomePhone
        msExchShadowOtherTelephone
        msExchShadowPager
        msExchShadowPhysicalDeliveryOfficeName
        msExchShadowPostalCode
        msExchShadowProxyAddresses
        msExchShadowSn
        msExchShadowSt
        msExchShadowStreetAddress
        msExchShadowTelephoneAssistant
        msExchShadowTelephoneNumber
        msExchShadowTitle
        msExchShadowWhenSoftDeletedTime
        msExchShadowWindowsLiveID
        msExchShadowWWWHomePage
        msExchSharingAnonymousIdentities
        msExchSharingPartnerIdentities
        msExchSharingPolicyLink
        msExchSignupAddresses
        msExchSMTPReceiveDefaultAcceptedDomainBL
        msExchStsRefreshTokensValidFrom
        msExchSupervisionDLBL
        msExchSupervisionDLLink
        msExchSupervisionOneOffBL
        msExchSupervisionOneOffLink
        msExchSupervisionUserBL
        msExchSupervisionUserLink
        msExchSyncAccountsPolicyDN
        msExchTeamMailboxExpiration
        msExchTeamMailboxOwners
        msExchTeamMailboxSharePointLinkedBy
        msExchTeamMailboxSharePointUrl
        msExchTeamMailboxShowInClientList
        msExchTenantCountry
        msExchTextMessagingState
        msExchThrottlingPolicyDN
        msExchTransportInboundSettings
        msExchTransportOutboundSettings
        msExchTransportRecipientSettingsFlags
        msExchTransportRuleTargetBL
        msExchTrustedDomainBL
        msExchTUIPassword
        msExchTUISpeed
        msExchTUIVolume
        msExchUCVoiceMailSettings
        msExchUGEventSubscriptionBL
        msExchUGEventSubscriptionLink
        msExchUGMemberBL
        msExchUGMemberLink
        msExchUMAddresses
        msExchUMAudioCodec
        msExchUMAudioCodec2
        msExchUMCallingLineIDs
        msExchUMDtmfMap
        msExchUMEnabledFlags
        msExchUMEnabledFlags2
        msExchUMFaxId
        msExchUMListInDirectorySearch
        msExchUMMailboxOVALanguage
        msExchUMMaxGreetingDuration
        msExchUMOperatorNumber
        msExchUMPhoneProvider
        msExchUMPinChecksum
        msExchUMRecipientDialPlanLink
        msExchUMServerWritableFlags
        msExchUMSpokenName
        msExchUMTemplateLink
        msExchUnifiedMailbox
        msExchUnmergedAttsPt
        msExchUsageLocation
        msExchUseOAB
        msExchUserAccountControl
        msExchUserBL
        msExchUserCulture
        msExchUserHoldPolicies
        msExchVersion
        msExchVoiceMailboxID
        msExchWhenMailboxCreated
        msExchWhenSoftDeletedTime
        msExchWindowsLiveID
        msIIS-FTPDir
        msIIS-FTPRoot
        mSMQDigests
        mSMQDigestsMig
        mSMQSignCertificates
        mSMQSignCertificatesMig
        msNPAllowDialin
        msNPCallingStationID
        msNPSavedCallingStationID
        msOrg-LeadersBL
        msPKIAccountCredentials
        msPKI-CredentialRoamingTokens
        msPKIDPAPIMasterKeys
        msPKIRoamingTimeStamp
        msRADIUSCallbackNumber
        msRADIUS-FramedInterfaceId
        msRADIUSFramedIPAddress
        msRADIUS-FramedIpv6Prefix
        msRADIUS-FramedIpv6Route
        msRADIUSFramedRoute
        msRADIUS-SavedFramedInterfaceId
        msRADIUS-SavedFramedIpv6Prefix
        msRADIUS-SavedFramedIpv6Route
        msRADIUSServiceType
        msRASSavedCallbackNumber
        msRASSavedFramedIPAddress
        msRASSavedFramedRoute
        msSFU30Name
        msSFU30NisDomain
        msSFU30PosixMemberOf
        msTSAllowLogon
        msTSBrokenConnectionAction
        msTSConnectClientDrives
        msTSConnectPrinterDrives
        msTSDefaultToMainPrinter
        msTSExpireDate
        msTSExpireDate2
        msTSExpireDate3
        msTSExpireDate4
        msTSHomeDirectory
        msTSHomeDrive
        msTSInitialProgram
        msTSLicenseVersion
        msTSLicenseVersion2
        msTSLicenseVersion3
        msTSLicenseVersion4
        msTSLSProperty01
        msTSLSProperty02
        msTSManagingLS
        msTSManagingLS2
        msTSManagingLS3
        msTSManagingLS4
        msTSMaxConnectionTime
        msTSMaxDisconnectionTime
        msTSMaxIdleTime
        msTSPrimaryDesktop
        msTSProfilePath
        msTSProperty01
        msTSProperty02
        msTSReconnectionAction
        msTSRemoteControl
        msTSSecondaryDesktops
        msTSWorkDirectory
        name
        netbootSCPBL
        networkAddress
        nonSecurityMemberBL
        ntPwdHistory
        nTSecurityDescriptor
        o
        objectCategory
        objectClass
        objectGUID
        objectSid
        objectVersion
        operatorCount
        otherFacsimileTelephoneNumber
        otherHomePhone
        otherIpPhone
        otherLoginWorkstations
        otherMailbox
        otherMobile
        otherPager
        otherTelephone
        otherWellKnownObjects
        ou
        ownerBL
        pager
        partialAttributeDeletionList
        partialAttributeSet
        personalPager
        personalTitle
        photo
        physicalDeliveryOfficeName
        pOPCharacterSet
        pOPContentFormat
        possibleInferiors
        postalAddress
        postalCode
        postOfficeBox
        preferredDeliveryMethod
        preferredLanguage
        preferredOU
        primaryGroupID
        primaryInternationalISDNNumber
        primaryTelexNumber
        profilePath
        protocolSettings
        proxiedObjectName
        proxyAddresses
        publicDelegates
        publicDelegatesBL
        pwdLastSet
        queryPolicyBL
        registeredAddress
        replicatedObjectVersion
        replicationSensitivity
        replicationSignature
        replPropertyMetaData
        replUpToDateVector
        repsFrom
        repsTo
        revision
        rid
        roomNumber
        sAMAccountName
        sAMAccountType
        scriptPath
        sDRightsEffective
        secretary
        securityIdentifier
        securityProtocol
        seeAlso
        serialNumber
        serverReferenceBL
        servicePrincipalName
        shadowExpire
        shadowFlag
        shadowInactive
        shadowLastChange
        shadowMax
        shadowMin
        shadowWarning
        showInAddressBook
        showInAdvancedViewOnly
        sIDHistory
        siteObjectBL
        sn
        st
        street
        streetAddress
        structuralObjectClass
        submissionContLength
        subRefs
        subSchemaSubEntry
        supplementalCredentials
        supportedAlgorithms
        systemFlags
        targetAddress
        telephoneAssistant
        telephoneNumber
        teletexTerminalIdentifier
        telexNumber
        terminalServer
        textEncodedORAddress
        thumbnailLogo
        thumbnailPhoto
        title
        tokenGroups
        tokenGroupsGlobalAndUniversal
        tokenGroupsNoGCAcceptable
        uid
        uidNumber
        unauthOrig
        unauthOrigBL
        unicodePwd
        unixHomeDirectory
        unixUserPassword
        unmergedAtts
        url
        userAccountControl
        userCert
        userCertificate
        userParameters
        userPassword
        userPKCS12
        userPrincipalName
        userSharedFolder
        userSharedFolderOther
        userSMIMECertificate
        userWorkstations
        uSNChanged
        uSNCreated
        uSNDSALastObjRemoved
        USNIntersite
        uSNLastObjRem
        uSNSource
        versionNumber
        wbemPath
        wellKnownObjects
        whenChanged
        whenCreated
        wWWHomePage
        x121Address
        x500uniqueIdentifier
         */ 
        #endregion
    }
}
